export const PlayerState = Object.freeze({
  IDLE: "IDLE",
  AUTO_RUN: "AUTO_RUN",
  JUMP_ASCEND: "JUMP_ASCEND",
  JUMP_DESCEND: "JUMP_DESCEND",
  STOMP_BOUNCE: "STOMP_BOUNCE",
  PHOTO_PENDING: "PHOTO_PENDING",
  PHOTO_MODAL: "PHOTO_MODAL",
  POWERUP_TRANSITION: "POWERUP_TRANSITION",
  SCRIPTED: "SCRIPTED",
  KISS_WAIT: "KISS_WAIT",
  GALLERY_MODAL: "GALLERY_MODAL",
  SPLIT_WAIT: "SPLIT_WAIT",
  EXITING: "EXITING",
  FLAG_LEAP: "FLAG_LEAP",
  TRANSITION: "TRANSITION",
  LEVEL_COMPLETE: "LEVEL_COMPLETE",
});

export const PlayerForm = Object.freeze({
  SMALL: "SMALL",
  BIG: "BIG",
  FIRE: "FIRE",
  COUPLE: "COUPLE",
  COUPLE_CAT: "COUPLE_CAT",
  COUPLE_FIRE: "COUPLE_FIRE",
  BABY_BUS: "BABY_BUS",
});

export const EnemyState = Object.freeze({
  ACTIVE: "ACTIVE",
  INVULNERABLE: "INVULNERABLE",
  SHELL_PAUSE: "SHELL_PAUSE",
  DYING: "DYING",
  REMOVED: "REMOVED",
  HIDDEN: "HIDDEN",
  EMERGING: "EMERGING",
  SHELL_WAIT: "SHELL_WAIT",
});

export const INPUT = Object.freeze({
  DOWN: "pointer_down",
  UP: "pointer_up",
  CANCEL: "pointer_cancel",
});

export const FORM_PREFIX = Object.freeze({
  SMALL: "groom_small",
  BIG: "groom_big",
  FIRE: "groom_fire",
  COUPLE: "wedding_pair",
  COUPLE_CAT: "wedding_pair_cat",
  COUPLE_FIRE: "wedding_pair_fire",
  BABY_BUS: "wedding_baby_bus",
});

export const PLAYER_FRAME_SIZE = Object.freeze({
  SMALL: { width: 32, height: 32 },
  BIG: { width: 32, height: 48 },
  FIRE: { width: 32, height: 48 },
  COUPLE: { width: 64, height: 64 },
  COUPLE_CAT: { width: 64, height: 64 },
  COUPLE_FIRE: { width: 64, height: 64 },
  BABY_BUS: { width: 128, height: 64 },
});

export const ASSET_PATHS = Object.freeze({
  groom_small_idle: "./assets/sprites/characters/groom_small_idle.png",
  groom_small_walk_a: "./assets/sprites/characters/groom_small_walk_a.png",
  groom_small_walk_b: "./assets/sprites/characters/groom_small_walk_b.png",
  groom_small_jump: "./assets/sprites/characters/groom_small_jump.png",
  groom_big_idle: "./assets/sprites/characters/groom_big_idle.png",
  groom_big_walk_a: "./assets/sprites/characters/groom_big_walk_a.png",
  groom_big_walk_b: "./assets/sprites/characters/groom_big_walk_b.png",
  groom_big_jump: "./assets/sprites/characters/groom_big_jump.png",
  groom_fire_idle: "./assets/sprites/characters/groom_fire_idle.png",
  groom_fire_walk_a: "./assets/sprites/characters/groom_fire_walk_a.png",
  groom_fire_walk_b: "./assets/sprites/characters/groom_fire_walk_b.png",
  groom_fire_jump: "./assets/sprites/characters/groom_fire_jump.png",
  bride_idle: "./assets/sprites/characters/bride_idle.png",
  bride_walk_a: "./assets/sprites/characters/bride_walk_a.png",
  bride_walk_b: "./assets/sprites/characters/bride_walk_b.png",
  bride_jump: "./assets/sprites/characters/bride_jump.png",
  wedding_pair_idle: "./assets/sprites/characters/wedding_pair_idle.png",
  wedding_pair_walk_a: "./assets/sprites/characters/wedding_pair_walk_a.png",
  wedding_pair_walk_b: "./assets/sprites/characters/wedding_pair_walk_b.png",
  wedding_pair_jump: "./assets/sprites/characters/wedding_pair_jump.png",
  wedding_pair_fire_idle: "./assets/sprites/characters/wedding_pair_fire_idle.png",
  wedding_pair_fire_walk_a: "./assets/sprites/characters/wedding_pair_fire_walk_a.png",
  wedding_pair_fire_walk_b: "./assets/sprites/characters/wedding_pair_fire_walk_b.png",
  wedding_pair_fire_jump: "./assets/sprites/characters/wedding_pair_fire_jump.png",
  wedding_kiss: "./assets/sprites/characters/wedding_kiss.png",
  groom_alpaca_idle: "./assets/sprites/characters/groom_alpaca_idle.png",
  groom_alpaca_walk_a: "./assets/sprites/characters/groom_alpaca_walk_a.png",
  groom_alpaca_walk_b: "./assets/sprites/characters/groom_alpaca_walk_b.png",
  groom_alpaca_jump: "./assets/sprites/characters/groom_alpaca_jump.png",
  wedding_pair_cat_idle: "./assets/sprites/characters/wedding_pair_cat_idle.png",
  wedding_pair_cat_walk_a: "./assets/sprites/characters/wedding_pair_cat_walk_a.png",
  wedding_pair_cat_walk_b: "./assets/sprites/characters/wedding_pair_cat_walk_b.png",
  wedding_pair_cat_jump: "./assets/sprites/characters/wedding_pair_cat_jump.png",
  mentor_idle: "./assets/sprites/characters/mentor_idle.png",
  mentor_run_right_a: "./assets/sprites/characters/mentor_run_right_a.png",
  mentor_run_right_b: "./assets/sprites/characters/mentor_run_right_b.png",
  mentor_run_left_a: "./assets/sprites/characters/mentor_run_left_a.png",
  mentor_run_left_b: "./assets/sprites/characters/mentor_run_left_b.png",
  mentor_wave_a: "./assets/sprites/characters/mentor_wave_a.png",
  mentor_wave_b: "./assets/sprites/characters/mentor_wave_b.png",
  wedding_baby_bus_idle: "./assets/sprites/characters/wedding_baby_bus_idle.png",
  wedding_baby_bus_drive_a: "./assets/sprites/characters/wedding_baby_bus_drive_a.png",
  wedding_baby_bus_drive_b: "./assets/sprites/characters/wedding_baby_bus_drive_b.png",
  // PlayerController uses the common walk/jump names. Keep aliases so the
  // BABY_BUS form can safely return from a scripted sequence to AUTO_RUN.
  wedding_baby_bus_walk_a: "./assets/sprites/characters/wedding_baby_bus_drive_a.png",
  wedding_baby_bus_walk_b: "./assets/sprites/characters/wedding_baby_bus_drive_b.png",
  wedding_baby_bus_jump: "./assets/sprites/characters/wedding_baby_bus_drive_a.png",
  proposal_offer_flower: "./assets/sprites/characters/proposal_offer_flower.png",
  proposal_kneel_hold_hand: "./assets/sprites/characters/proposal_kneel_hold_hand.png",
  proposal_present_ring: "./assets/sprites/characters/proposal_present_ring.png",
  proposal_celebrate_petals: "./assets/sprites/characters/proposal_celebrate_petals.png",
  couple_heart_pose: "./assets/sprites/characters/couple_heart_pose.png",
  couple_embrace_heart: "./assets/sprites/characters/couple_embrace_heart.png",
  flagpole_static: "./assets/sprites/events/flagpole_static.png",
  flag_cloth: "./assets/sprites/events/flag_cloth.png",
  groom_hold_pole: "./assets/sprites/events/groom_hold_pole.png",
  groom_slide_pole: "./assets/sprites/events/groom_slide_pole.png",
  heart_red: "./assets/sprites/events/heart_red.png",
  firework_orange_small: "./assets/sprites/events/firework_orange_small.png",
  firework_orange_medium: "./assets/sprites/events/firework_orange_medium.png",
  firework_orange_large: "./assets/sprites/events/firework_orange_large.png",
  coin_heart_shower_00: "./assets/sprites/events/coin_heart_shower_00.png",
  coin_heart_shower_01: "./assets/sprites/events/coin_heart_shower_01.png",
  coin_heart_shower_02: "./assets/sprites/events/coin_heart_shower_02.png",
  coin_heart_shower_03: "./assets/sprites/events/coin_heart_shower_03.png",
  coin_heart_shower_04: "./assets/sprites/events/coin_heart_shower_04.png",
  coin_heart_shower_05: "./assets/sprites/events/coin_heart_shower_05.png",
  coin_heart_shower_06: "./assets/sprites/events/coin_heart_shower_06.png",
  coin_heart_shower_07: "./assets/sprites/events/coin_heart_shower_07.png",
  coin_heart_shower_08: "./assets/sprites/events/coin_heart_shower_08.png",
  coin_heart_shower_09: "./assets/sprites/events/coin_heart_shower_09.png",
  coin_heart_shower_10: "./assets/sprites/events/coin_heart_shower_10.png",
  coin_heart_shower_11: "./assets/sprites/events/coin_heart_shower_11.png",
  heart_red_96_reveal_30: "./assets/sprites/events/heart_red_96_reveal_30.png",
  heart_red_96_reveal_50: "./assets/sprites/events/heart_red_96_reveal_50.png",
  heart_red_96_reveal_80: "./assets/sprites/events/heart_red_96_reveal_80.png",
  heart_red_96_reveal_100: "./assets/sprites/events/heart_red_96_reveal_100.png",
  goomba_walk_a: "./assets/sprites/enemies/goomba_walk_a.png",
  goomba_walk_b: "./assets/sprites/enemies/goomba_walk_b.png",
  koopa_walk_a: "./assets/sprites/enemies/koopa_walk_a.png",
  koopa_walk_b: "./assets/sprites/enemies/koopa_walk_b.png",
  koopa_retract: "./assets/sprites/enemies/koopa_retract.png",
  koopa_shell_idle: "./assets/sprites/enemies/koopa_shell_idle.png",
  koopa_shell_move: "./assets/sprites/enemies/koopa_shell_move.png",
  bowser_mouth_closed: "./assets/sprites/enemies/bowser_mouth_closed.png",
  bowser_mouth_open: "./assets/sprites/enemies/bowser_mouth_open.png",
  piranha_open: "./assets/sprites/enemies/piranha_open.png",
  piranha_closed: "./assets/sprites/enemies/piranha_closed.png",
  super_mushroom: "./assets/sprites/items/super_mushroom.png",
  fire_flower: "./assets/sprites/items/fire_flower.png",
  attack_fire_0: "./assets/sprites/items/attack_fire_0.png",
  attack_fire_1: "./assets/sprites/items/attack_fire_1.png",
  attack_fire_2: "./assets/sprites/items/attack_fire_2.png",
  attack_fire_3: "./assets/sprites/items/attack_fire_3.png",
  coin_0: "./assets/sprites/scenes/coin_0.png",
  coin_1: "./assets/sprites/scenes/coin_1.png",
  coin_2: "./assets/sprites/scenes/coin_2.png",
  coin_3: "./assets/sprites/scenes/coin_3.png",
  question_block: "./assets/sprites/scenes/question_block.png",
  flag: "./assets/sprites/scenes/flag.png",
  yungang_grottoes_buddha: "./assets/sprites/scenes/yungang_grottoes_buddha.png",
  tokyo_tower: "./assets/sprites/scenes/tokyo_tower.png",
  flag_uk: "./assets/sprites/scenes/flag_uk.png",
  flag_ireland: "./assets/sprites/scenes/flag_ireland.png",
  flag_turkey: "./assets/sprites/scenes/flag_turkey.png",
  flag_japan: "./assets/sprites/scenes/flag_japan.png",
  flag_china: "./assets/sprites/scenes/flag_china.png",
  groom_787_airplane: "./assets/sprites/scenes/groom_787_airplane.png",
  eurasia_world_map: "./assets/sprites/scenes/eurasia_world_map.png",
  couple_high_speed_train: "./assets/sprites/scenes/couple_high_speed_train.png",
  tabby_cat_side: "./assets/sprites/scenes/tabby_cat_side.png",
  palm_tree: "./assets/sprites/scenes/palm_tree.png",
  graduation_cap: "./assets/sprites/scenes/graduation_cap.png",
  couple_hot_air_balloon: "./assets/sprites/scenes/couple_hot_air_balloon.png",
});
